import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#E3F2FD', 
      },
      title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#0D47A1', 
        marginBottom: 25,
        textAlign: 'center', 
      },
      input: {
        height: 50,
        borderColor: '#BBDEFB', 
        borderWidth: 1,
        borderRadius: 10,
        paddingLeft: 15,
        fontSize: 16,
        backgroundColor: '#FFFFFF', 
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 2, 
      },
      subtitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#1565C0', 
        marginBottom: 15,
      },
      contactItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        backgroundColor: '#F5F5F5',
        borderRadius: 10,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
      },
      contactName: {
        fontSize: 16,
        fontWeight: '500',
        color: '#424242',
      },
      noContacts: {
        color: '#757575',
        fontStyle: 'italic',
        textAlign: 'center',
        marginTop: 20,
      },
      addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 20,
        padding: 15,
        backgroundColor: '#E3F2FD', 
        borderRadius: 10,
        borderColor: '#64B5F6',
        borderWidth: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 2,
      },
      addButtonText: {
        marginLeft: 10,
        fontSize: 16,
        fontWeight: '500',
        color: '#1565C0',
      },
      saveButton: {
        padding: 15,
        backgroundColor: '#1E88E5', 
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 4,
      },
      saveButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
      },
});